### ISSUE TITLE
Natverse install fails due to "?

### ISSUE THREAD

**Issue by linneweb** [natverse/natverse#22]
Hey I am tryin to update my natverse install to newest version with a fresh install.

System Windows, R4.1.0

* checking for file 'C:\Users\Gerit\AppData\Local\Temp\RtmpQrBrtn\remotes2fbcb3149e5\natverse-natverse-246a410/DESCRIPTION' ... OK
* preparing 'natverse':
* checking DESCRIPTION meta-information ... ERROR
Malformed Authors@R field:
  <text>:13:24: unexpected symbol
12:       person(given = "Alexander”,
13:              family = "Bates

I noticed that in the Description file Alex has changed to Alexander and that the type of " has changed since the last version. I am not sure if that is really the mistake, but it would be great if you could look into it.

Best 
Gerit

**Comment by jefferis** [comment]
Thanks so much @linneweb. You are absolutely correct that the error is in DESCRIPTION. @alexanderbates should have checked the package before pushing and unfortunately the travis builds which would normally catch this are offline. I have pushed a fix now.

**Comment by linneweb** [comment]
Thank you so much! Now everything is great again and I had absolutely no problem!
